### ISSUE TITLE
 Pytorch-ONNX-TFLite转化问题

### ISSUE THREAD

**Issue by gepu0221** [lee-man/movenet-pytorch#3]
您好，请问你已经成功实现 Pytorch-ONNX-TFLite转化了吗，我尝试使用以下环境：
pytorch=1.9.0
tensorflow==2.4.1
onnx==1.8.0
onnx-tf==1.7.0
在使用脚本https://github.com/lee-man/movenet-pytorch/blob/main/torch2onnx.py 转化时，onnx2pb会报错，错误如下，能麻烦告知下使用的具体环境版本吗？
谢谢！
Traceback (most recent call last):
  File "torch2onnx.py", line 85, in <module>
    main()
  File "torch2onnx.py", line 62, in main
    tf_rep.export_graph(tf_model_path)
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/onnx_tf/backend_rep.py", line 115, in export_graph
    signatures=self.tf_module.__call__.get_concrete_function(
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
    graph_function, _ = self._maybe_define_function(args, kwargs)
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
    func_graph_module.func_graph_from_py_func(
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
    out = weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3887, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
    raise e.ag_error_metadata.to_exception(e)
RuntimeError: in user code:

    /home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/onnx_tf/backend_tf_module.py:98 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/onnx_tf/backend.py:289 _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    /home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/onnx_tf/handlers/handler.py:58 handle  *
        cls.args_check(node, **kwargs)
    /home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/onnx_tf/handlers/backend/resize.py:125 args_check  *
        exception.OP_UNSUPPORTED_EXCEPT(
    /home/gepu/anaconda3/envs/movenet2/lib/python3.8/site-packages/onnx_tf/common/exception.py:50 __call__  *
        raise self._func(self.get_message(op, framework))

    RuntimeError: Resize coordinate_transformation_mode=pytorch_half_pixel is not supported in Tensorflow.

**Comment by lee-man** [comment]
@gepu0221 我更新了代码，你可以试一下。不过现在onnx转tf有一些问题，比如会引入很多的tranpose，我还在找解决方法。
